{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [],
   "source": [
    "from tkinter import *\n",
    "from tkinter import messagebox \n",
    "root= Tk()\n",
    "root.geometry(\"250x400+300+300\")\n",
    "root.resizable(0,0)\n",
    "root.title(\"Calculator\")\n",
    "val= \"\"\n",
    "A=0\n",
    "operator = \"\"\n",
    "def b1_is_clicked():\n",
    "    global val \n",
    "    val=val\n",
    "    val=val+\"1\"\n",
    "    data.set(val)\n",
    "    \n",
    "def b2_is_clicked():\n",
    "    global val \n",
    "    val=val\n",
    "    val=val+\"2\"\n",
    "    data.set(val)\n",
    "    \n",
    "def b3_is_clicked():\n",
    "    global val \n",
    "    val=val\n",
    "    val=val+\"3\"\n",
    "    data.set(val) \n",
    "    \n",
    "def b4_is_clicked():\n",
    "    global val \n",
    "    val=val\n",
    "    val=val+\"4\"\n",
    "    data.set(val) \n",
    "    \n",
    "def b5_is_clicked():\n",
    "    global val \n",
    "    val=val\n",
    "    val=val+\"5\"\n",
    "    data.set(val)\n",
    "    \n",
    "def b6_is_clicked():\n",
    "    global val \n",
    "    val=val\n",
    "    val=val+\"6\"\n",
    "    data.set(val)\n",
    "    \n",
    "def b6_is_clicked():\n",
    "    global val \n",
    "    val=val\n",
    "    val=val+\"6\"\n",
    "    data.set(val)\n",
    "    \n",
    "def b7_is_clicked():\n",
    "    global val \n",
    "    val=val\n",
    "    val=val+\"7\"\n",
    "    data.set(val)\n",
    "    \n",
    "def b8_is_clicked():\n",
    "    global val \n",
    "    val=val\n",
    "    val=val+\"8\"\n",
    "    data.set(val)\n",
    "    \n",
    "def b9_is_clicked():\n",
    "    global val \n",
    "    val=val\n",
    "    val=val+\"9\"\n",
    "    data.set(val)\n",
    "    \n",
    "def b0_is_clicked():\n",
    "    global val\n",
    "    val=val\n",
    "    val=val+\"0\"\n",
    "    data.set(val)\n",
    "    \n",
    "def b1_is_clicked():\n",
    "    global val \n",
    "    val=val\n",
    "    val=val+\"1\"\n",
    "    data.set(val)\n",
    "    \n",
    "def btpl_is_clicked():\n",
    "    global A\n",
    "    global operator,val \n",
    "    A = int(val)\n",
    "    operater = \"+\"\n",
    "    val = val + \"+\"\n",
    "    data.set(val)\n",
    "    \n",
    "def btmin_is_clicked():\n",
    "    global A \n",
    "    global operator,val\n",
    "    A = int(val)\n",
    "    operater = \"-\"\n",
    "    val = val + \"-\"\n",
    "    data.set(val)\n",
    "    \n",
    "def btmul_is_clicked():\n",
    "    global A\n",
    "    global operater,val\n",
    "    A = int(val)\n",
    "    operater = \"*\"\n",
    "    val=val + \"*\"\n",
    "    data.set(val)\n",
    "    \n",
    "def btdiv_is_clicked():    \n",
    "    global A\n",
    "    global operater,val\n",
    "    A = int(val)\n",
    "    operater = \"/\"\n",
    "    val=val + \"/\"\n",
    "    data.set(val)\n",
    "    \n",
    "def btc_is_clicked():\n",
    "    global A\n",
    "    global operater,val\n",
    "    A = 0\n",
    "    operater = \"\"\n",
    "    val = \"\"\n",
    "    data.set(val)\n",
    "\n",
    "def result():\n",
    "    global A,operater,val\n",
    "    val2= val\n",
    "    if operater == \"+\":\n",
    "        x = int((val2.split(\"+\")[1]))\n",
    "        C = A+x\n",
    "        val=str(C)\n",
    "        data.set(C)\n",
    "    \n",
    "    \n",
    "    if operater == \"-\":\n",
    "        x = int((val2.split(\"-\")[1]))\n",
    "        C = A-x\n",
    "        val=str(C)\n",
    "        data.set(C)\n",
    "    \n",
    "    if operater == \"*\":\n",
    "        x = int((val2.split(\"*\")[1]))\n",
    "        C = A*x\n",
    "        val=str(C)\n",
    "        data.set(C)\n",
    "    if  operater ==\"/\":\n",
    "        x = int((val2.split(\"/\")[1]))\n",
    "        if x==0:\n",
    "            messagebox.showerror(\"Error\",\"can't divide number by 0\")\n",
    "            A = \"\"\n",
    "            val=\"\"\n",
    "            data.set(val)\n",
    "        else:\n",
    "            C = int(A/x)\n",
    "            data.set(C)\n",
    "            \n",
    "data=StringVar()\n",
    "l=Label(root,text=\"Label\",anchor = SE ,font=('Verdana',20),textvariable = data,background = \"blue\",fg=\"yellow\",)\n",
    "l.pack(expand=True,fill = \"both\")\n",
    "f1=Frame(root)\n",
    "f1.pack(expand=True,fill=\"both\")\n",
    "f2=Frame(root)\n",
    "f2.pack(expand=True,fill=\"both\")\n",
    "f3=Frame(root)\n",
    "f3.pack(expand=True,fill=\"both\")\n",
    "f4=Frame(root)\n",
    "f4.pack(expand=True,fill=\"both\")\n",
    "#button for frame 1\n",
    "\n",
    "b1= Button(f1,text = \"1\",font=(\"Verdana\",22),relief = GROOVE,border =0,command = b1_is_clicked)\n",
    "b1.pack(side=LEFT,expand= True,fill=\"both\",)\n",
    "\n",
    "b2= Button(f2,text = \"2\",font=(\"Verdana\",22),relief = GROOVE,border =0,command = b2_is_clicked)\n",
    "b2.pack(side=LEFT,expand= True,fill=\"both\",)\n",
    "\n",
    "b3= Button(f3,text = \"3\",font=(\"Verdana\",22),relief = GROOVE,border =0,command = b3_is_clicked)\n",
    "b3.pack(side=LEFT,expand= True,fill=\"both\",)\n",
    "\n",
    "btpl= Button(f1,text = \"+\",font=(\"Verdana\",22),relief = GROOVE,border =0,command = btpl_is_clicked)\n",
    "btpl.pack(side=LEFT,expand= True,fill=\"both\",)\n",
    "\n",
    "# button for frame 2\n",
    "b4= Button(f2,text = \"4\",font=(\"Verdana\",22),relief = GROOVE,border =0,command = b4_is_clicked)\n",
    "b4.pack(side=LEFT,expand= True,fill=\"both\",)\n",
    "\n",
    "b5= Button(f2,text = \"5\",font=(\"Verdana\",22),relief = GROOVE,border =0,command = b5_is_clicked)\n",
    "b5.pack(side=LEFT,expand= True,fill=\"both\",)\n",
    "\n",
    "b6= Button(f2,text = \"6\",font=(\"Verdana\",22),relief = GROOVE,border =0,command = b6_is_clicked)\n",
    "b6.pack(side=LEFT,expand= True,fill=\"both\",)\n",
    "\n",
    "btmin= Button(f2,text = \"-\",font=(\"Verdana\",22),relief = GROOVE,border =0,command = btmin_is_clicked)\n",
    "btmin.pack(side=LEFT,expand= True,fill=\"both\",)\n",
    "\n",
    "#button for frame 3\n",
    "\n",
    "b7= Button(f3,text = \"7\",font=(\"Verdana\",22),relief = GROOVE,border =0,command = b7_is_clicked)\n",
    "b7.pack(side=LEFT,expand= True,fill=\"both\",)\n",
    "\n",
    "b8= Button(f3,text = \"8\",font=(\"Verdana\",22),relief = GROOVE,border =0,command = b8_is_clicked)\n",
    "b8.pack(side=LEFT,expand= True,fill=\"both\",)\n",
    "\n",
    "b9= Button(f3,text = \"9\",font=(\"Verdana\",22),relief = GROOVE,border =0,command = b9_is_clicked)\n",
    "b9.pack(side=LEFT,expand= True,fill=\"both\",)\n",
    "\n",
    "btmul= Button(f1,text = \"*\",font=(\"Verdana\",22),relief = GROOVE,border =0,command = btmul_is_clicked)\n",
    "btmul.pack(side=LEFT,expand= True,fill=\"both\",)\n",
    "\n",
    "\n",
    "#button for frame 4 \n",
    "btc= Button(f4,text = \"C\",font=(\"Verdana\",22),relief = GROOVE,border =0,command = btc_is_clicked)\n",
    "btc.pack(side=LEFT,expand= True,fill=\"both\",)\n",
    "\n",
    "bt0= Button(f1,text = \"0\",font=(\"Verdana\",22),relief = GROOVE,border =0,command = b0_is_clicked)\n",
    "bt0.pack(side=LEFT,expand= True,fill=\"both\",)\n",
    "\n",
    "bteq= Button(f4,text = \"=\",font=(\"Verdana\",22),relief = GROOVE,border =0,command = result)\n",
    "bteq.pack(side=LEFT,expand= True,fill=\"both\",)\n",
    "\n",
    "btdiv= Button(f4,text = \"/\",font=(\"Verdana\",22),relief = GROOVE,border =0,command =btdiv_is_clicked)\n",
    "btdiv.pack(side= LEFT,expand= True,fill=\"both\",)\n",
    "\n",
    "root.mainloop()    \n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
